name: Deploy NestJS API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/MyFitGuideAPI
        env:
          RSYNC_RSH: "ssh -p ${{ secrets.EC2_PORT }} -o StrictHostKeyChecking=no"

      - name: Install dependencies on EC2 and restart app with PM2
        run: |
          ssh -t -p ${{ secrets.EC2_PORT }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            source ~/.profile
            source ~/.bashrc
            cd ~/MyFitGuideAPI
            npm install --production
            pm2 reload myfitguide-api || pm2 start dist/main.js --name myfitguide-api
          EOF
