name: Deploy NestJS API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          export SSH_DIR=$(mktemp -d)
          echo "SSH dir: $SSH_DIR"
          # Escribir la clave privada preservando saltos de línea correctamente
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > "$SSH_DIR/id_rsa"
          chmod 600 "$SSH_DIR/id_rsa"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> "$SSH_DIR/known_hosts"
          ssh-keyscan -H github.com >> "$SSH_DIR/known_hosts"
          echo "SSH_DIR=$SSH_DIR" >> $GITHUB_ENV

      - name: Pull latest code on EC2
        shell: bash
        run: |
          ssh -i $SSH_DIR/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/MyFitGuideAPI &&
            git fetch origin main &&
            git reset --hard origin/main
          "

      - name: Install dependencies on EC2
        shell: bash
        run: |
          ssh -i $SSH_DIR/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            export NVM_DIR=\"$HOME/.nvm\" &&
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" &&
            cd /home/ubuntu/MyFitGuideAPI &&
            npm install
          "

      - name: Build project on EC2
        shell: bash
        run: |
          ssh -i $SSH_DIR/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            export NVM_DIR=\"$HOME/.nvm\" &&
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" &&
            cd /home/ubuntu/MyFitGuideAPI &&
            npm run build
          "

      - name: Restart pm2 on EC2
        shell: bash
        run: |
          ssh -i $SSH_DIR/id_rsa -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            export NVM_DIR=\"$HOME/.nvm\" &&
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\" &&
            pm2 restart myfitguide-api || pm2 start dist/main.js --name myfitguide-api
          "
