name: Deploy NestJS API to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > $HOME/.ssh/id_ed25519
          chmod 600 $HOME/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts
          ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts

      - name: Debug SSH Setup
        shell: bash
        run: |
          ls -la $HOME/.ssh/
          head -n 3 $HOME/.ssh/id_ed25519
          cat $HOME/.ssh/known_hosts

      - name: Deploy to EC2
        shell: bash
        run: |
          ssh -i $HOME/.ssh/id_ed25519 -o StrictHostKeyChecking=yes ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "bash -c '
            export NVM_DIR=\"$HOME/.nvm\"
            [ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"
            cd /home/ubuntu/MyFitGuideAPI &&
            git fetch origin main &&
            git reset --hard origin/main &&
            npm install &&
            npm run build &&
            pm2 restart myfitguide-api || pm2 start dist/main.js --name myfitguide-api
          '"
